# Generated by Django 3.2.8 on 2021-11-03 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='username',
        ),
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.CharField(default=1, max_length=255, verbose_name='Email Adresiniz'),
            preserve_default=False,
        ),
    ]
