# Generated by Django 3.2.4 on 2021-11-20 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20211120_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='dogulduguil',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='nomre',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='olke',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
