# Generated by Django 3.2.4 on 2021-11-20 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20211120_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='dogulduguil',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='oxudugucalisdigi',
            field=models.CharField(max_length=255),
        ),
    ]
