# Generated by Django 3.2.4 on 2021-11-20 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_alter_userprofile_nomre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='nomre',
            field=models.IntegerField(null=True),
        ),
    ]
