# Generated by Django 3.2.9 on 2021-11-22 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_alter_userprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='nomre',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
