# Generated by Django 3.2.9 on 2021-11-22 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_alter_userprofile_nomre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='nomre',
            field=models.IntegerField(null=True),
        ),
    ]
