# Generated by Django 3.2.8 on 2021-10-24 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kitab',
            name='zaman',
        ),
    ]
