# Generated by Django 3.2.8 on 2021-10-24 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_remove_kitab_zaman'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitab',
            name='yazilma_tarixi',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
