# Generated by Django 3.2.8 on 2021-10-30 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_alter_kitab_mehsulkodu'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_picture',
            field=models.ImageField(default=1, upload_to='sekiller/'),
            preserve_default=False,
        ),
    ]
