# Generated by Django 3.2.8 on 2021-10-30 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_category_category_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='text',
            field=models.TextField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
